import type { Character, GameSet } from "@/types/game";

// ─── Mock Game Set ────────────────────────────────────────────────────────────

export const MOCK_GAME_SET: GameSet = {
  id: "mock-set-001",
  title: "Classic Office Pack",
  theme: "classic_office",
  imageStyle: "pixar",
  status: "draft",
  characterCount: 24,
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-01-01T00:00:00Z",
};

// ─── Mock Characters ──────────────────────────────────────────────────────────
// 24 characters with deliberate variety across all gameplay traits.

export const MOCK_CHARACTERS: Character[] = [
  {
    id: "c-001",
    gameSetId: "mock-set-001",
    displayName: "Alex",
    referenceImageUrls: [],
    attributes: {
      hairLength: "short",
      hairColor: "black",
      hairTexture: "straight",
      facialHair: "none",
      glasses: "round",
      hat: "none",
      eyeColor: "brown",
      expression: "smiling_teeth",
      topColor: "blue",
      outfitType: "shirt",
      accessory: "coffee_mug",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-002",
    gameSetId: "mock-set-001",
    displayName: "Barb",
    referenceImageUrls: [],
    attributes: {
      hairLength: "long",
      hairColor: "blonde",
      hairTexture: "wavy",
      facialHair: "none",
      glasses: "none",
      hat: "none",
      eyeColor: "blue",
      expression: "smiling_closed",
      topColor: "red",
      outfitType: "hoodie",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-003",
    gameSetId: "mock-set-001",
    displayName: "Carlos",
    referenceImageUrls: [],
    attributes: {
      hairLength: "buzz",
      hairColor: "brown",
      hairTexture: "straight",
      facialHair: "beard",
      glasses: "square",
      hat: "none",
      eyeColor: "brown",
      expression: "serious",
      topColor: "black",
      outfitType: "suit",
      accessory: "laptop",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-004",
    gameSetId: "mock-set-001",
    displayName: "Dana",
    referenceImageUrls: [],
    attributes: {
      hairLength: "medium",
      hairColor: "red",
      hairTexture: "curly",
      facialHair: "none",
      glasses: "none",
      hat: "cap",
      eyeColor: "green",
      expression: "smiling_teeth",
      topColor: "green",
      outfitType: "tshirt",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-005",
    gameSetId: "mock-set-001",
    displayName: "Ezra",
    referenceImageUrls: [],
    attributes: {
      hairLength: "bald",
      hairColor: "hidden",
      hairTexture: "none",
      facialHair: "goatee",
      glasses: "round",
      hat: "none",
      eyeColor: "hazel",
      expression: "neutral",
      topColor: "white",
      outfitType: "shirt",
      accessory: "coffee_mug",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-006",
    gameSetId: "mock-set-001",
    displayName: "Farida",
    referenceImageUrls: [],
    attributes: {
      hairLength: "long",
      hairColor: "black",
      hairTexture: "straight",
      facialHair: "none",
      glasses: "sunglasses",
      hat: "none",
      eyeColor: "not_visible",
      expression: "neutral",
      topColor: "purple",
      outfitType: "jacket",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-007",
    gameSetId: "mock-set-001",
    displayName: "Greg",
    referenceImageUrls: [],
    attributes: {
      hairLength: "short",
      hairColor: "grey",
      hairTexture: "straight",
      facialHair: "moustache",
      glasses: "none",
      hat: "none",
      eyeColor: "grey",
      expression: "serious",
      topColor: "blue",
      outfitType: "suit",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-008",
    gameSetId: "mock-set-001",
    displayName: "Hana",
    referenceImageUrls: [],
    attributes: {
      hairLength: "medium",
      hairColor: "brown",
      hairTexture: "wavy",
      facialHair: "none",
      glasses: "square",
      hat: "beanie",
      eyeColor: "brown",
      expression: "smiling_closed",
      topColor: "orange",
      outfitType: "hoodie",
      accessory: "laptop",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-009",
    gameSetId: "mock-set-001",
    displayName: "Idris",
    referenceImageUrls: [],
    attributes: {
      hairLength: "short",
      hairColor: "black",
      hairTexture: "afro",
      facialHair: "stubble",
      glasses: "none",
      hat: "none",
      eyeColor: "brown",
      expression: "smiling_teeth",
      topColor: "yellow",
      outfitType: "tshirt",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-010",
    gameSetId: "mock-set-001",
    displayName: "Jen",
    referenceImageUrls: [],
    attributes: {
      hairLength: "short",
      hairColor: "dyed",
      hairTexture: "straight",
      facialHair: "none",
      glasses: "round",
      hat: "cap",
      eyeColor: "blue",
      expression: "neutral",
      topColor: "black",
      outfitType: "jacket",
      accessory: "coffee_mug",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-011",
    gameSetId: "mock-set-001",
    displayName: "Kenji",
    referenceImageUrls: [],
    attributes: {
      hairLength: "medium",
      hairColor: "black",
      hairTexture: "straight",
      facialHair: "none",
      glasses: "none",
      hat: "none",
      eyeColor: "brown",
      expression: "smiling_teeth",
      topColor: "white",
      outfitType: "shirt",
      accessory: "laptop",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-012",
    gameSetId: "mock-set-001",
    displayName: "Luna",
    referenceImageUrls: [],
    attributes: {
      hairLength: "long",
      hairColor: "brown",
      hairTexture: "curly",
      facialHair: "none",
      glasses: "none",
      hat: "beanie",
      eyeColor: "green",
      expression: "smiling_closed",
      topColor: "red",
      outfitType: "hoodie",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-013",
    gameSetId: "mock-set-001",
    displayName: "Marcus",
    referenceImageUrls: [],
    attributes: {
      hairLength: "bald",
      hairColor: "hidden",
      hairTexture: "none",
      facialHair: "beard",
      glasses: "square",
      hat: "none",
      eyeColor: "brown",
      expression: "neutral",
      topColor: "blue",
      outfitType: "suit",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-014",
    gameSetId: "mock-set-001",
    displayName: "Nadia",
    referenceImageUrls: [],
    attributes: {
      hairLength: "medium",
      hairColor: "blonde",
      hairTexture: "straight",
      facialHair: "none",
      glasses: "none",
      hat: "none",
      eyeColor: "blue",
      expression: "serious",
      topColor: "purple",
      outfitType: "jacket",
      accessory: "laptop",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-015",
    gameSetId: "mock-set-001",
    displayName: "Omar",
    referenceImageUrls: [],
    attributes: {
      hairLength: "short",
      hairColor: "brown",
      hairTexture: "wavy",
      facialHair: "moustache",
      glasses: "none",
      hat: "cap",
      eyeColor: "hazel",
      expression: "smiling_teeth",
      topColor: "green",
      outfitType: "tshirt",
      accessory: "coffee_mug",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-016",
    gameSetId: "mock-set-001",
    displayName: "Priya",
    referenceImageUrls: [],
    attributes: {
      hairLength: "long",
      hairColor: "black",
      hairTexture: "straight",
      facialHair: "none",
      glasses: "round",
      hat: "none",
      eyeColor: "brown",
      expression: "smiling_closed",
      topColor: "orange",
      outfitType: "shirt",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-017",
    gameSetId: "mock-set-001",
    displayName: "Quinn",
    referenceImageUrls: [],
    attributes: {
      hairLength: "buzz",
      hairColor: "blonde",
      hairTexture: "straight",
      facialHair: "stubble",
      glasses: "none",
      hat: "none",
      eyeColor: "grey",
      expression: "neutral",
      topColor: "black",
      outfitType: "hoodie",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-018",
    gameSetId: "mock-set-001",
    displayName: "Remy",
    referenceImageUrls: [],
    attributes: {
      hairLength: "medium",
      hairColor: "grey",
      hairTexture: "wavy",
      facialHair: "goatee",
      glasses: "square",
      hat: "none",
      eyeColor: "blue",
      expression: "serious",
      topColor: "white",
      outfitType: "suit",
      accessory: "laptop",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-019",
    gameSetId: "mock-set-001",
    displayName: "Sana",
    referenceImageUrls: [],
    attributes: {
      hairLength: "long",
      hairColor: "red",
      hairTexture: "curly",
      facialHair: "none",
      glasses: "none",
      hat: "beanie",
      eyeColor: "green",
      expression: "smiling_teeth",
      topColor: "yellow",
      outfitType: "jacket",
      accessory: "coffee_mug",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-020",
    gameSetId: "mock-set-001",
    displayName: "Tomas",
    referenceImageUrls: [],
    attributes: {
      hairLength: "short",
      hairColor: "brown",
      hairTexture: "straight",
      facialHair: "beard",
      glasses: "none",
      hat: "cap",
      eyeColor: "brown",
      expression: "neutral",
      topColor: "blue",
      outfitType: "tshirt",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-021",
    gameSetId: "mock-set-001",
    displayName: "Uma",
    referenceImageUrls: [],
    attributes: {
      hairLength: "medium",
      hairColor: "black",
      hairTexture: "afro",
      facialHair: "none",
      glasses: "sunglasses",
      hat: "none",
      eyeColor: "not_visible",
      expression: "smiling_closed",
      topColor: "red",
      outfitType: "jacket",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-022",
    gameSetId: "mock-set-001",
    displayName: "Viktor",
    referenceImageUrls: [],
    attributes: {
      hairLength: "short",
      hairColor: "white",
      hairTexture: "straight",
      facialHair: "moustache",
      glasses: "round",
      hat: "none",
      eyeColor: "grey",
      expression: "serious",
      topColor: "purple",
      outfitType: "suit",
      accessory: "coffee_mug",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-023",
    gameSetId: "mock-set-001",
    displayName: "Wren",
    referenceImageUrls: [],
    attributes: {
      hairLength: "long",
      hairColor: "dyed",
      hairTexture: "straight",
      facialHair: "none",
      glasses: "none",
      hat: "beanie",
      eyeColor: "blue",
      expression: "smiling_teeth",
      topColor: "green",
      outfitType: "hoodie",
      accessory: "laptop",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "c-024",
    gameSetId: "mock-set-001",
    displayName: "Xander",
    referenceImageUrls: [],
    attributes: {
      hairLength: "buzz",
      hairColor: "brown",
      hairTexture: "straight",
      facialHair: "stubble",
      glasses: "square",
      hat: "cap",
      eyeColor: "hazel",
      expression: "neutral",
      topColor: "orange",
      outfitType: "tshirt",
      accessory: "none",
    },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
];
